### ISSUE TITLE
Pick your ingredients View

### ISSUE THREAD

**Issue by 22193** [GewoonRene/yourownpizza#16]
@22193 Build the ingredients View on Flutter in Dart.

**Comment by StanHaakman** [comment]
Hoever ben je hier nu mee idriss?

**Comment by rhuibertsjr** [comment]
@StanHaakman Ik assign mezelf hieraan, totdat Idriss update geeft.

**Comment by rhuibertsjr** [comment]
fixed in latest pullrequest
