### ISSUE TITLE
Bottom Sheet

### ISSUE THREAD

**Issue by ghost** [GewoonRene/yourownpizza#21]
Making the bottom bar

**Comment by rhuibertsjr** [comment]
@maessmit Hoe staat het ervoor met deze issue? Kan je deze vandaag pushen?
Aangezien deze in meerdere view's gebruikt word.

**Comment by ghost** [comment]
> @maessmit Hoe staat het ervoor met deze issue? Kan je deze vandaag pushen?
> Aangezien deze in meerdere view's gebruikt word.

@GewoonRene Ik ben er nog mee bezig maar heb wel een begin gemaakt.

**Comment by rhuibertsjr** [comment]
Ait deze is gemerged met master.
