### ISSUE TITLE
Backend

### ISSUE THREAD

**Issue by ghost** [GewoonRene/yourownpizza#32]
adding the backend to the app

**Comment by rhuibertsjr** [comment]
In de  [feature/drinks branch](https://github.com/GewoonRene/yourownpizza/blob/feature/dranken/lib/View/drinks/helpers/DrinkManager.dart) zit het bestandje DrinksManager, dit is een kleine Api die ik heb gemaakt voor deze view. Zullen we proberen hierop uit te breiden?

**Comment by ghost** [comment]
@GewoonRene Ja vind ik goed, alleen heb niet echt heel veel met api's gewerkt dus wordt een beetje uit volgen

**Comment by rhuibertsjr** [comment]
pullrequest later will fix this but I will close this for now
