### ISSUE TITLE
Plan van Aanpak

### ISSUE THREAD

**Issue by rhuibertsjr** [GewoonRene/yourownpizza#4]

**Comment by rhuibertsjr** [comment]
@StanHaakman Jow welke font en font-size heb je gebruikt?

en ik heb hier nog een typo gevonden.

![image](https://user-images.githubusercontent.com/31036753/71075994-475f0d00-2185-11ea-8e1e-e9d18fac053f.png)

**Comment by StanHaakman** [comment]
Ik heb Proxima nova gebruikt en de kopjes font-size 18 en de gewone font-size 11.
Ik loop de tekst nog een keertje na op nog meer spelfouten of formulieringsfouten

**Comment by rhuibertsjr** [comment]
Fixed in latest pullrequest (#10)
